'use client';

// Import React hooks for state and side effects
import { useState, useEffect } from 'react';
// Import Next.js navigation hooks to get route params and handle routing
import { useParams, useRouter } from 'next/navigation';
// Import Link component for client-side navigation
import Link from 'next/link';
// Import icons from lucide-react for back arrow and save button
import { ArrowLeft, Save } from 'lucide-react';
// Import the custom VoiceInput component for speech-to-text
import VoiceInput from '@/components/VoiceInput';

// Emoji map for detected emotions – translates emotion strings to visual emojis
const emotionEmoji: Record<string, string> = {
  joy: '😊', sadness: '😢', anger: '😠', fear: '😨', love: '❤️', surprise: '😲', neutral: '😐',
  anxious: '😰', anxiety: '😰', calm: '😌', hopeful: '🙏', grateful: '🙏', gratitude: '🙏',
  lonely: '😔', loneliness: '😔', proud: '😎', pride: '😎', confused: '🤔', overwhelmed: '😫',
  tired: '😴', excited: '🤩', excitement: '🤩', peaceful: '😌', frustrated: '😤', frustration: '😤',
  grief: '😭', guilt: '😞', hope: '🌟', contentment: '😊', melancholic: '😔'
};

// Main component for editing an existing journal entry
export default function EditEntryPage() {
  // Extract the entry ID from the dynamic route parameter
  const { id } = useParams();
  // Router instance for programmatic navigation after save
  const router = useRouter();

  // State variables for form fields
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [subject, setSubject] = useState('');
  // Current emotion stored in the entry (from database)
  const [currentEmotion, setCurrentEmotion] = useState('neutral');
  // Emotion detected by AI after saving
  const [detectedEmotion, setDetectedEmotion] = useState('');
  // Summary text generated by AI for the detected emotion
  const [emotionSummary, setEmotionSummary] = useState('');
  // Loading states
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  // Whether voice input is active (passed to VoiceInput component)
  const [isListening, setIsListening] = useState(false);

  // Load existing entry data when component mounts or id changes
  useEffect(() => {
    fetch(`/api/journal-entries/${id}`)
      .then(res => res.json())
      .then(data => {
        // Populate form with fetched data
        setTitle(data.title || '');
        setContent(data.content || '');
        setSubject(data.topics || 'General');
        setCurrentEmotion(data.emotion || 'neutral');
        setLoading(false);
      })
      .catch(() => setLoading(false)); // Hide loader on error
  }, [id]);

  /**
   * Handles each chunk of recognised speech from VoiceInput.
   * Because VoiceInput now sends only the *incremental* text (the new characters since the last chunk),
   * we simply append it to the existing content.
   *
   * This preserves any text the user has typed (or already voiced) and
   * builds the spoken sentence correctly without duplication.
   */
  const handleTranscript = (voiceText: string) => {
    setContent((prevContent) => prevContent + voiceText);
  };

  // Handle form submission (update entry via PUT request)
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Trim and validate required fields
    const trimmedTitle = title?.trim() || '';
    const trimmedContent = content?.trim() || '';
    if (!trimmedTitle || !trimmedContent) {
      setError('Please fill both fields.');
      return;
    }
    // Default subject to "General" if empty
    const finalSubject = subject.trim() === '' ? 'General' : subject.trim();

    setSubmitting(true);
    try {
      // Send PUT request to update the entry
      const res = await fetch(`/api/journal-entries/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title: trimmedTitle, content: trimmedContent, subject: finalSubject }),
      });
      if (!res.ok) throw new Error('Update failed');

      // Parse response containing AI-detected emotion and summary
      const data = await res.json();
      setDetectedEmotion(data.detectedEmotion || '');
      setEmotionSummary(data.emotionSummary || '');

      // Redirect to journal page after a short delay so user can see the emotion result
      setTimeout(() => router.push('/journal'), 3000);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setSubmitting(false);
    }
  };

  // Show a loading spinner while fetching the entry data
  if (loading) return (
    <div className="min-h-screen flex items-center justify-center">
      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-white"></div>
    </div>
  );

  // Main render: edit form with background image and glass-morphism card
  return (
    <main className="min-h-screen flex items-center justify-center px-4 py-12" style={{ backgroundImage: "url('https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=2070&auto=format')", backgroundSize: 'cover', backgroundPosition: 'center' }}>
      <div className="max-w-3xl w-full glass-card p-8">
        {/* Back link to journal list */}
        <Link href="/journal" className="inline-flex items-center gap-2 text-white/80 hover:text-white transition mb-6">
          <ArrowLeft size={18} /> Back to Journal
        </Link>

        <h1 className="text-3xl font-bold text-white mb-2 text-center">Edit Entry</h1>
        <p className="text-white/70 mb-6 text-center">Update your thoughts and feelings.</p>

        {/* Display error message if any */}
        {error && <div className="bg-red-500/20 text-red-200 p-3 rounded-lg mb-6">{error}</div>}

        {/* Show current emotion (from DB) before saving – only when not displaying a newly detected emotion */}
        {!detectedEmotion && (
          <div className="bg-white/10 text-white p-3 rounded-lg mb-6 text-center">
            Current emotion: {emotionEmoji[currentEmotion] || '🔍'} <strong className="capitalize">{currentEmotion}</strong>
            <p className="text-xs text-white/50 mt-1">Will be re-detected automatically when you save.</p>
          </div>
        )}

        {/* After saving, show the newly detected emotion and AI summary, then redirect */}
        {detectedEmotion && (
          <div className="bg-white/20 border border-white/30 text-white p-4 rounded-xl mb-6 text-center space-y-1">
            <p className="text-lg font-semibold">
              ✨ Updated emotion: {emotionEmoji[detectedEmotion] || '🔍'} <span className="capitalize">{detectedEmotion}</span>
            </p>
            {emotionSummary && <p className="text-sm text-white/80 italic">"{emotionSummary}"</p>}
            <p className="text-xs text-white/50">Redirecting to journal...</p>
          </div>
        )}

        {/* Edit form */}
        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Title input */}
          <div>
            <label className="block text-sm font-medium text-white/80 mb-1">Title</label>
            <input
              type="text"
              value={title}
              onChange={e => setTitle(e.target.value)}
              className="w-full px-4 py-3 rounded-xl bg-white/20 border border-white/30 text-white placeholder-white/50 focus:outline-none focus:ring-2 focus:ring-white/50 transition"
              disabled={submitting}
            />
          </div>

          {/* Subject/topics input (for analytics) */}
          <div>
            <label className="block text-sm font-medium text-white/80 mb-1">Subject (for analytics)</label>
            <input
              type="text"
              value={subject}
              onChange={e => setSubject(e.target.value)}
              placeholder="e.g., Work, Health, Dreams..."
              className="w-full px-4 py-3 rounded-xl bg-white/20 border border-white/30 text-white placeholder-white/50 focus:outline-none focus:ring-2 focus:ring-white/50"
            />
          </div>

          {/* Journal content textarea with voice input button */}
          <div>
            <div className="flex justify-between items-center mb-1">
              <label className="block text-sm font-medium text-white/80">Your Journal Entry</label>
              <VoiceInput
                onTranscript={handleTranscript}
                isListening={isListening}
                setIsListening={setIsListening}
              />
            </div>
            <textarea
              rows={12}
              value={content}
              onChange={e => setContent(e.target.value)}
              className="w-full px-4 py-3 rounded-xl bg-white/20 border border-white/30 text-white placeholder-white/50 focus:outline-none focus:ring-2 focus:ring-white/50 transition"
              placeholder="Write or speak your entry..."
              disabled={submitting}
              spellCheck={true}
            />
            <p className="text-xs text-white/50 mt-2">✨ Emotion will be detected automatically when you save.</p>
          </div>

          {/* Action buttons: Cancel and Save */}
          <div className="flex justify-end gap-3">
            <Link href="/journal" className="px-6 py-2 rounded-full border border-white/30 text-white/80 hover:bg-white/10 transition">
              Cancel
            </Link>
            <button
              type="submit"
              disabled={submitting}
              className="inline-flex items-center gap-2 px-6 py-2 rounded-full bg-white/20 hover:bg-white/30 text-white font-semibold transition disabled:opacity-50"
            >
              <Save size={18} /> {submitting ? 'Analysing your feelings...' : 'Save Changes'}
            </button>
          </div>
        </form>
      </div>
    </main>
  );
}